export enum CommunityType {
    GLOBAL = "GLOBAL",
    INTERNATIONAL = "INTERNATIONAL",
    NATIONAL = "NATIONAL",
    REGIONAL = "REGIONAL",
    SUBREGIONAL = "SUBREGIONAL",
    LOCALITY = "LOCALITY",
}